# @desc ESLint configration
# @changed 2020.12.08, 12:36
#
# @see:
#
# - https://eslint.org/docs/rules/
# - https://eslint.org/docs/user-guide/configuring#specifying-environments
# - [JavaScript Standard Style](https://standardjs.com/rules.html)
#
# react rules:
#
# - https://github.com/yannickcr/eslint-plugin-react#list-of-supported-rules
# - https://github.com/jsx-eslint/eslint-plugin-jsx-a11y#supported-rules

parser: 'babel-eslint'
extends:
  - 'plugin:react/all'
  - 'eslint:recommended'
plugins:
  - 'react'
  - 'react-hooks'
env:
  browser: true
parserOptions:
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: '16.13'
rules:
  # linebreak-style: [2, 'unix']
  arrow-body-style: 0
  brace-style: 0
  class-methods-use-this: 0
  consistent-return: 0
  import/prefer-default-export: 0
  jsx-a11y/label-has-associated-control: 0
  jsx-a11y/label-has-for: 0
  max-len: 0
  no-case-declarations: 0
  no-console: 'warn' # disable for debug mode with `/* eslint-disable no-console */`
  no-debugger: 'warn' # disable for debug mode with `/* eslint-disable no-debugger */`
  no-param-reassign: 0
  no-shadow: 0
  object-curly-newline: 0
  operator-linebreak: 0
  padded-blocks: 0
  prefer-template: 0
  # react/forbid-prop-types: 0
  # react/jsx-handler-names: 0
  # react/jsx-max-depth: 0
  # react/no-array-index-key: 0
  # react/no-multi-comp: 0
  react/require-default-props: 0
  react-hooks/exhaustive-deps: 'warn'
  react-hooks/rules-of-hooks: 'error'
  react/destructuring-assignment: 0
  react/forbid-component-props: 0
  react/jsx-boolean-value: 0
  react/jsx-closing-bracket-location: 0
  react/jsx-first-prop-new-line: 0
  react/jsx-fragments: 0
  react/jsx-handler-names: 0
  react/jsx-indent-props: 0
  react/jsx-indent: 0
  react/jsx-max-props-per-line: 0
  react/jsx-no-literals: 0
  react/jsx-one-expression-per-line: 0
  react/jsx-props-no-spreading: 0
  react/jsx-sort-props: 0
  react/jsx-tag-spacing: 0
  react/jsx-uses-react: 'error'
  react/jsx-uses-vars: 'error'
  react/no-did-update-set-state: 0
  react/no-set-state: 0
  react/no-unused-state: 0
  react/prop-types: 0
  react/sort-comp: 0
  react/sort-prop-types: 0
  react/style-prop-object: 0
  require-jsdoc: 0
  requireSemicolons: 0
  spaced-comment: 0
  react/function-component-definition: 0
    # - 1
    # - namedComponents: "function-declaration" | "function-expression" | "arrow-function",
    # - unnamedComponents: "function-expression" | "arrow-function"
  quotes:
    - 'warn'
    - 'single'
  indent:
    - 'warn'
    - 2
    - SwitchCase: 1
  # indent:
  #   - 2
  #   - 'warn'
  object-curly-spacing:
    - 'warn'
    - 'always'
  space-before-function-paren:
    - 'warn'
    - 'never'
  keyword-spacing:
    - 'warn'
    -
      before: true
      after: true
  no-unused-vars:
    - 'warn'
    -
      vars: 'local'
      varsIgnorePattern: '^_'
  semi:
    - 'warn'
    - 'always'
  no-trailing-spaces:
    - 2
    -
      skipBlankLines: true
overrides:
  -  # default js
    files: '**/*.{js,jsx}'
    env:
      browser: true
      commonjs: true
      es6: true
      node: true
    # globals:
    #   process: true
